name: docker deployment
on: push
jobs:
  docker_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: docker config
        uses: docker/setup-buildx-action@v3
      - name: docker build & push
        run: |
          docker build -t sriramravi477/javaapp:${{ github.run_id }} .
          docker login -u ${{ secrets.DOCKER_CRED_USR }} -p ${{ secrets.DOCKER_CRED_PSW }}
          docker push sriramravi477/javaapp:${{ github.run_id }}
