name: docker deployment
on: push
jobs:
  docker_deployment:
    runs-on: ubuntu-lastest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: docker config
        uses: docker/setup-buildx-action@v3
      - name: docker build & push
        run: |
          docker build -t javaapp .
          docker image ls | grep javaapp
